# Generated by Django 4.0.3 on 2022-03-31 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('time_limit_minutes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='company name', max_length=50)),
                ('city', models.CharField(default='', max_length=25)),
                ('street', models.CharField(default='', max_length=25)),
                ('description', models.CharField(default='', max_length=50)),
                ('logo', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=25)),
                ('description', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(default='', max_length=25)),
                ('post_start_date', models.DateTimeField()),
                ('post_end_date', models.DateTimeField()),
                ('remote', models.BooleanField(default=False)),
                ('salary', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='api.assignment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.company')),
            ],
        ),
    ]
