# Generated by Django 4.0.3 on 2022-03-29 11:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_post_start_date_job_post_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.AddField(
            model_name='job',
            name='assignment_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='jobs', to='api.assignment'),
        ),
        migrations.AddField(
            model_name='job',
            name='company_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.company'),
            preserve_default=False,
        ),
    ]
