# Generated by Django 4.0.3 on 2022-03-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_job_assignment_remove_job_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='assignment_id',
            new_name='assignment',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='company_id',
            new_name='company',
        ),
    ]
